language: nopde_js

nopde_js: 
  - "12.16.2"

branches:
  only:
    - master

script: 
  - ng build --prod
  
before_script:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token  $FIREBASE_TOKEN